version: '3.9'

services:
  chunk-embed:
    build:
      context: ./chunk-embed
    ports:
      - "8000:8000"
    container_name: squawk-chunk-embed
    env_file:
      - ./chunk-embed/.env  
    volumes:
      - ./chunk-embed:/app   # Mount local code for hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  chat:
    build:
      context: ./chat
    ports:
      - "8080:8000"
    container_name: squawk-chat
    env_file:
      - ./chat/.env 
    volumes:
      - ./chat:/app   # Mount local code for hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload